name: Node.js CI

on:

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Zip folder creation
        run: |
          mkdir app_artifact
          zip -r webapp . -x ".git/" ".github/" "node_modules/*" "package-lock.json"
          mv webapp.zip app_artifact
      - name: Validate Packer
        run: |
          packer init ami.pkr.hcl
          packer validate ami.pkr.hcl
